final String burjKhalifaDetails =
    "The Burj Khalifa[a] (known as the Burj Dubai prior to its inauguration) is a skyscraper in Dubai, United Arab Emirates. It is the world's tallest structure. With a total height of 829.8 m (2,722 ft, or just over half a mile) and a roof height (excluding antenna, but including a 242.6 m spire)[2] of 828 m (2,717 ft), the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009, surpassing Taipei 101, the previous holder of that status.[3][4]\nConstruction of the Burj Khalifa began in 2004, with the exterior completed five years later in 2009. The primary structure is reinforced concrete and some of the structural steel for the building originated from the Palace of the Republic in East Berlin, the former East German parliament.[5] The building was opened in 2010 as part of a new development called Downtown Dubai. It was designed to be the centerpiece of large-scale, mixed-use development.";
final String burjArabDetails =
    "The Burj Al Arab (Arabic: برج العرب, lit. 'Arab Tower') is a luxury hotel in Dubai, United Arab Emirates.[8] Developed and managed by Jumeirah, it is one of the tallest hotels in the world, although 39% of its total height is made up of non-occupiable space.[9][10][11] Burj Al Arab stands on an artificial island that is 280 m (920 ft) from Jumeirah Beach and is connected to the mainland by a private curving bridge. The shape of the structure is designed to resemble the sail of a dhow.[12] It has a helipad near the roof, at a height of 210 m (689 ft) above ground.";

final String palmJumairaDetails =
    "The Palm Jumeirah is an archipelago of artificial islands on the Persian Gulf in Jumeirah, Dubai, United Arab Emirates. It is part of a larger series of developments called the Palm Islands, including Palm Jebel Ali and the Dubai Islands, which, when completed, will together increase Dubai's shoreline by a total of 520 kilometres (320 mi).[3] It has a population of over 25,000[4] as of 2022.[5]\nThe islands were created using land reclamation. As the name implies, they were created to resemble a palm tree and are roughly divided into three areas: 'trunk', 'fronds', and 'outer crescent'. The trunk is a mixed commercial and residential area, the fronds are reserved for residential homes and villas, while the outer crescent is used for luxury and upscale resorts.[6]";
final String grandMosqueAbuDhbaiDetail =
    "The Grand Mosque was constructed between 1994 and 2007 and was inaugurated in December 2007.[3] The building complex measures approximately 290 by 420 m (950 by 1,380 ft), covering an area of more than 12 hectares (30 acres), excluding exterior landscaping and vehicle parking. The main axis of the building is rotated about 12° south of true west, aligning it in the direction of the Kaaba in Mecca, Saudi Arabia.\nThe project was launched by the late president of the U.A.E., Sheikh Zayed bin Sultan Al Nahyan, who wanted to establish a structure that would unite the cultural diversity of the Islamic world with the historical and modern values of architecture and art.[4] In 2004, Sheikh Zayed died and was buried in the courtyard of the mosque.";
final String tajmahalDetails =
    "The Taj Mahal (/ˌtɑːdʒ məˈhɑːl, ˌtɑːʒ -/ TAHJ mə-HAHL, TAHZH -⁠, Hindi: [taːdʒ ˈmɛɦ(ɛ)l]; lit. 'Crown of the Palace') is an ivory-white marble mausoleum on the right bank of the river Yamuna in Agra, Uttar Pradesh, India. It was commissioned in 1631 by the fifth Mughal emperor, Shah Jahan (r. 1628–1658) to house the tomb of his beloved wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself. The tomb is the centrepiece of a 17-hectare (42-acre) complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall.";
final String amazonForestDetail =
    "The Amazon rainforest,[a] also called Amazon jungle or Amazonia, is a moist broadleaf tropical rainforest in the Amazon biome that covers most of the Amazon basin of South America. This basin encompasses 7,000,000 km2 (2,700,000 sq mi),[2] of which 6,000,000 km2 (2,300,000 sq mi) are covered by the rainforest.[3] This region includes territory belonging to nine nations and 3,344 indigenous territories.\nThe majority of the forest, 60%, is in Brazil, followed by Peru with 13%, Colombia with 10%, and with minor amounts in Bolivia, Ecuador, French Guiana, Guyana, Suriname, and Venezuela. Four nations have 'Amazonas' as the name of one of their first-level administrative regions, and France uses the name 'Guiana Amazonian Park' for French Guiana's protected rainforest area. The Amazon represents over half of Earth's remaining rainforests,[4] and comprises the largest and most biodiverse tract of tropical rainforest in the world, with an estimated 390 billion individual trees in about 16,000 species.[5]";
final String seaDetails =
    "A sea is a large body of salty water. There are particular seas and the sea. The sea commonly refers to the World Ocean, the wider body of seawater. Particular seas are either marginal seas, second-order sections of the oceanic sea (e.g. the Mediterranean Sea), or certain large, nearly landlocked bodies of water.\nThe salinity of water bodies varies widely, being lower near the surface and the mouths of large rivers and higher in the depths of the ocean; however, the relative proportions of dissolved salts vary little across the oceans. The most abundant solid dissolved in seawater is sodium chloride. The water also contains salts of magnesium, calcium, potassium, and mercury, amongst many other elements, some in minute concentrations. A wide variety of organisms, including bacteria, protists, algae, plants, fungi, and animals live in the seas, which offers a wide range of marine habitats and ecosystems, ranging vertically from the sunlit surface and shoreline to the great depths and pressures of the cold, dark abyssal zone, and in latitude from the cold waters under polar ice caps to the warm waters of coral reefs in tropical regions. Many of the major groups of organisms evolved in the sea and life may have started there.";
final String desertDetails =
    "A desert is a landscape where little precipitation occurs and, consequently, living conditions create unique biomes and ecosystems. The lack of vegetation exposes the unprotected surface of the ground to denudation. About one-third of the land surface of the Earth is arid or semi-arid. This includes much of the polar regions, where little precipitation occurs, and which are sometimes called polar deserts or 'cold deserts'. Deserts can be classified by the amount of precipitation that falls, by the temperature that prevails, by the causes of desertification or by their geographical location.[1]";
